"""add unique participant billing period constraint

Revision ID: 3dfb67eddef4
Revises: cf5a9794f378
Create Date: 2026-09-04 11:23:25.117464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dfb67eddef4'
down_revision = 'cf5a9794f378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_participant_billing_period', ['participant_id', 'billing_period'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_participant_billing_period', type_='unique')

    # ### end Alembic commands ###
