"""add family member to service requests

Revision ID: cf5a9794f378
Revises: a99001b0662f
Create Date: 2026-09-04 10:56:33.494216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf5a9794f378'
down_revision = 'a99001b0662f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_member_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'family_members', ['family_member_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('family_member_id')

    # ### end Alembic commands ###
